services:
  - type: web
    name: zona-update-api
    env: python
    region: frankfurt
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python server.py"
    plan: free
